; generated by OrcaSlicer 1.9.0
; total estimated time: 2h 30m 0s
; filament cost = 0.50, 0.75, 0.25, 0.10
; filament used [g] = 25.50, 35.75, 12.25, 5.10
; filament used [mm] = 8500, 11916, 4083, 1700
; total layers: 100

; layer 0
T0
G1 X10 Y10 Z0.2 E1.0
; layer 1
T1  
G1 X20 Y20 Z0.4 E2.0
; layer 10
T2
G1 X30 Y30 Z2.0 E3.0
; layer 20
T3
G1 X40 Y40 Z4.0 E4.0
; layer 50
T0
G1 X50 Y50 Z10.0 E5.0