; Generated by OrcaSlicer
; filament_colour = #FF6600;#00AE42;#0087D4;#F7EC49
; layer_height = 0.2

G28 ; home
G1 Z0.2 F1200

; Layer 0
T0
G1 X10 Y10 F3000
G1 X20 Y10 E1.0

; Layer 1
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z0.4
T1
G1 X20 Y20 E2.0

; Layer 2
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
G1 Z0.6
T2
G1 X10 Y20 E3.0

; Layer 3
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
G1 Z0.8
T3
G1 X10 Y10 E4.0

M104 S0 ; turn off extruder
M140 S0 ; turn off bed
M84 ; disable motors